### PR TITLE
Adapt for couchbase 4.0.0

### PR DESCRIPTION
**Pull request by tgross**
@misterbisson @max123 this PR makes this Docker container work for couchbase 4.0. It also includes ensuring that the data, query, and index services are all up and running on all nodes during cluster-init and add-node steps.

### CODE REVIEW

**Comment by misterbisson** [comment]
Darn, I'm not sure how I missed this all this time.

I like what's here. I'm working on adding health checks in https://github.com/misterbisson/triton-couchbase/pull/2/. My thinking is to wrap that up, then resolve the conflicts I've created against this and integrate the changes in https://github.com/misterbisson/triton-couchbase/pull/2/files#diff-c51d61b06f43189c9c52d541086bd1b0, then this can become the new default.

**Comment by tgross** [comment]
For the couchbase benchmarking, we have both versions of CB. Do we want to maybe update this so that we can build either, or perhaps just keep this on its own branch?

**Comment by misterbisson** [comment]
This is part of https://github.com/misterbisson/triton-couchbase/issues/5

**Comment by misterbisson** [comment]
Closing this in favor of https://github.com/misterbisson/triton-couchbase/pull/8

**Pull request closed without merging**
